### ISSUE TITLE
Don't crash if `~/.clojure` could not be created

### ISSUE THREAD

**Issue by AndreTheHunter** [axrs/cljog#31]
Running `cljog` in https://github.com/jesims/build-bus locally with https://github.com/AndreTheHunter/dotfiles/blob/master/bin/docker-here tries to create a `.clojure` and `.cljog` directory.

```sh
$ wget https://raw.githubusercontent.com/axrs/cljog/master/example-scripts/echo.clj
$ docker-here jesiio/build-bus
$ cljog
cljog: Initialising config file: /home/node/.cljog
touch: cannot touch '/home/node/.cljog': Permission denied
$cljog echo.clj
mkdir: cannot create directory ‘/home/node/.clojure’: Permission denied
```

**Comment by axrs** [comment]
Most of the defaults require config.
`--version` doesn't
`cljog path/to/script.clj`  doesn't require config.

**Comment by axrs** [comment]
With version `0.4.0` (https://github.com/axrs/cljog/releases/tag/0.4.0)

cljog exits with code 1 if clojure is not found:

```
/project # ./cljog
cljog: Clojure tools not found. Refer https://clojure.org/guides/deps_and_cli
/project # echo $?
1
```

and does not attempt to create a config file if it doesn't require one. 

The `.clojure` file is created by the clojure cli tools.
